### PR TITLE
Fix some non-canonical NaNs in SIMD testsuite

### PR DESCRIPTION
**Pull request by abrown**
See https://github.com/WebAssembly/simd/pull/239.

### CODE REVIEW

**Comment by sbc100** [comment]
Normally we update the tests using the `./update-testsuite.sh` at the top level of this repo.   Maybe there is a reason not to do that in this case?

**Comment by binji** [comment]
It looks like it was...?

**Comment by sbc100** [comment]
I would expect PR title and description contain specific information if the script was used, no?

**Comment by sbc100** [comment]
Oh I see .. the git commit message itself does show this, its not not the same as the PR message.  My bad.  LGTM.

**Comment by sbc100** [comment]
When we squash this, which message do we use?  I think probably the automatic one, since its consistent with the rest of the history here...?

**Comment by abrown** [comment]
I don't think this needs to be squashed; if you just "rebase and merge" the history will have the auto-generated commit message and this PR will contain the context for why the update was made.

**Comment by sbc100** [comment]
We prefer linear history with one commit per PR here I believe.  (At least I do :)  

Thats why we set "squash and merge" as the default in the UI,

**Comment by sbc100** [comment]
Actually rebase and merge seems fine.. its still linear.

**Comment by sbc100** [comment]
I did rebase and merge and it looks like the information in PR itself was discarded and only the commit message actually landed.   I guess github throw away PR info during "rebase and merge"?  Ho hum.

**Comment by abrown** [comment]
Thanks; yeah the history should be linear but GitHub must do some magic somehow to keep track of commits to PRs because you can see what PR the commit came from if you [navigate to it directly](https://github.com/WebAssembly/testsuite/commit/21a10bc5942aeb328a057fa54820d3ffb5e7f144):

image

**Pull request merged**
