### PR TITLE
update repos

### PR DESCRIPTION
**Pull request by sbc100**
spec: e3a3c12f51221daaa901691e674d7ff990029122
  simd: 6740657c4a88a73046bc982ce4530d83937bf322
  bulk-memory-operations: 77db9426ff00eb7490e39548eb1e907ba98fec45
  nontrapping-float-to-int-conversions: 95b9dffdbb759b0f8de5db4ad23531680da5c123

### CODE REVIEW

**Comment by abrown** [comment]
@sbc100, thanks for doing this; I tried earlier this week and gave up when I ran into the merge conflicts you fixed in #11. One question: I can't find the SIMD hash (`6740657c4a88a73046bc982ce4530d83937bf322`) anywhere in my git logs or [on GitHub](https://github.com/webassembly/simd/commits); is there any chance that the SIMD commit was modified in some way that changed the hash? I see 6 files different when I do a `diff ` between the SIMD tests here and those in the SIMD repo--this could be because the SIMD repo just merged some new code but without a matching commit I feel less confident about that.

**Comment by sbc100** [comment]
i could have been doing some local experiments that time I guess.  I will do another update now and very the hash this time.   Maybe I'll convert them to URL so that are linked in github too.

**Comment by sbc100** [comment]
Latest update: #12

**Comment by sbc100** [comment]
It looks like there has always been a bug in the script such that the SHA1 patterns reported in the commit message don't match actual commits because the represent merge commits and that the result of merging each proposal with the spec repo.

For example take this commit: 
https://github.com/WebAssembly/testsuite/commit/21aff300ae02d43caec4a8589dad810c7a23caf6

If references a non-existent commit in the reference-types repo.

**Comment by sbc100** [comment]
Fixed in: https://github.com/WebAssembly/testsuite/pull/13

**Comment by abrown** [comment]
Nice!

**Pull request merged**
