### PR TITLE
Add annotation repo

### PR DESCRIPTION
**Pull request by sbc100**
Also add an ability to update just certain repos.

  annotations:
    https://github.com/WebAssembly/annotations/commit/1a33be6b

This change was automatically generated by `update-testsuite.sh`

### CODE REVIEW

**Comment by sunfishcode** [comment]
Would you mind adding a message to the generated commit message that lets readers know when the user opted to update only some repos?

It seems desirable to keep the testsuite repo itself as a mindless mirror, not something that decides for itself which repos to update.

**Comment by sbc100** [comment]
Would you rather I also updated all the other repos are part of this CL too?

**Comment by sunfishcode** [comment]
Yes. Would you mind changing this PR so that it just adds the `annotations` repo to the list, and doesn't update the tests at all? Once that's in, we can do a normal autogenerated "update all the repos" PR once that lands. That'd be tidier than adding an option to selectively update some of the repos and not others.

**Comment by sunfishcode** [comment]
This is mostly subsumed by #21 and #22; the one part that isn't is the change to allow updating some repos and not others. Unless someone specifically needs that, I think it'd be good to leave that out, to keep the focus on just being a simple "mirror everything" script.

**Pull request closed without merging**
