### PR TITLE
Add a CI workflow for auto-updating this repository

### LINKED ISSUE #84: Automating updates to this repository?
Would there be interest in perhaps configuring a github action to automatically run `update-testsuite.sh`, perhaps weekly, and make PRs? It could also range from auto-merging changes to the repository to just make a PR and let a human manually approve and merge.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit adds `.github/workflows/autoupdate.yml` to this repository which is scheduled to run once a week on Wednesday around noon PST (assuming I got the time zones right). This workflow will run the `./update-testsuite.sh` script and if it makes a commit it'll make a PR to this repository.

The motivation for this is to ensure that this repository doesn't lag behind too far upstream proposals and making it as easy as possible to land updates (ideally "just hit the big green button").

This commit updates some words in the `README.md` about the update process and additionally updates the script to not fail if no tests need an update.

An example pull request [looks like this][pr] and an example workflow which runs but didn't actually end up updating anything [looks like this][noop].

[pr]: https://github.com/alexcrichton/testsuite/pull/1
[noop]: https://github.com/alexcrichton/testsuite/actions/runs/9522240608/job/26251380263

Closes #84

### CODE REVIEW

**Comment by alexcrichton** [comment]
If it's not already enabled I'd also recommend a repository admin enables the "Automatically delete head branches" setting in the "General" tab of settings for this repository. That'll help ensure that branches don't stick around forever and get cleaned up after merging.

**Comment by tlively** [comment]
Looks like "Automatically delete head branches" is already enabled 👍

**Review by tlively — COMMENTED** [review]
This is super cool. How do the auth and permissions work for the `gh` command? Do we need to provision a new access token or is that built into GitHub Actions?

**Comment by alexcrichton** [comment]
This uses the built-in token to GitHub Actions which I believe is, by default, able to make PRs and write to the repository like this. I didn't do any custom configuration in my fork to test this out. I think the main consequence is that PRs created by GitHub Actions don't get actions themselves run on the PR itself, but this repository doesn't have that configured anyway so there's no issue there

**Comment by tlively** [comment]
Sounds good. This LGTM, but perhaps someone who is more familiar with this repo wants to take a look? @sunfishcode?

**Review by sunfishcode — APPROVED** [review]
Looks good to me.

**Comment by alexcrichton** [comment]
I'll note I don't have merge access so if someone could merge for me that'd be appreciated

**Pull request merged**
