### PR TITLE
Update repos

### PR DESCRIPTION
**Pull request by abrown**
spec:
    https://github.com/WebAssembly/spec/commit/ce89050a
  simd:
    https://github.com/WebAssembly/simd/commit/770ce643
  memory64:
    https://github.com/WebAssembly/memory64/commit/521927c2

This change was automatically generated by `update-testsuite.sh`

### CODE REVIEW

**Comment by abrown** [comment]
@sbc100, I see the following error from `update-testsuite.sh` that probably means that things are getting out of sync in a majority of repositories:

`!! failed to update repos:  threads exception-handling gc bulk-memory-operations host-bindings reference-types function-references`

What to do? Do those merge conflicts get fixed here or does this mean those repositories should be asked to merge/rebase something?

**Comment by sbc100** [comment]
Normally we would go ahead and land this change as is and file bugs in each of the repro that contain merge conflicts. 

Once the downstream folks merge from upstream and resolve their conflicts you can then re-run the script.

**Review by sbc100 — APPROVED** [review]
rubberstamp lgtm

**Comment by abrown** [comment]
Makes sense; can you merge? I don't think I have permissions.

**Pull request merged**
