### PR TITLE
Revert "Update repos"

### PR DESCRIPTION
**Pull request by aardappel**
This reverts commit baa396f9f8c55206be6d54f3a7caa2be663c6ca9.

This last commit had changes of both SIMD and Memory64 in it, which caused problems down-stream in WABT.
I will follow this up with a new PR that just brings in Memory64

### CODE REVIEW

**Comment by sunfishcode** [comment]
This is meant to be a mirror repository, where updates are mostly automatic, without tracking whether a particular repo update needs to be held back for a particular downstream. Is it possible to work around the issues on the wabt side?

**Comment by aardappel** [comment]
@sunfishcode WABT uses this repo as a submodule, so it is all or nothing. I just wasted a lot of time trying to fix issues produced by multiple proposals at once, which wasn't very productive.

**Comment by aardappel** [comment]
here's the followup: https://github.com/WebAssembly/testsuite/pull/36

**Comment by darinmorrison** [comment]
> @sunfishcode WABT uses this repo as a submodule, so it is all or nothing. I just wasted a lot of time trying to fix issues produced by multiple proposals at once, which wasn't very productive.

One problem is that there are other projects using the testsuite that have already been updated. Rolling back the changes on `master` is going to cause problems for those other projects.

A better alternative would be to create a `wabt` specific branch (either in this repo or elsewhere) that rolls back the changes and then update the submodule in the `wabt` repo to point to that instead of `master`.

I would also mention that I fixed all the SIMD-related breakage for `wabt` in the PR [here](https://github.com/WebAssembly/wabt/pull/1553).

**Comment by aardappel** [comment]
@darinmorrison ok, well lets then just get your PR merged, I'll rebase on that instead.

**Pull request closed without merging**
